In [4]:
import re
import pandas as pd
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [5]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading punkt_tab: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading wordnet: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading omw-1.4: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

False

In [6]:
stop_words =set(stopwords.words('english'))
lemmatizer= WordNetLemmatizer()

def clean_text(text):
    text= text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return " ".join(tokens)

In [7]:
df = pd.read_csv("../dataset/cleaned_dataset.csv")
df

                                                     text        class
0       Ex Wife Threatening SuicideRecently I left my ...      suicide
1       Am I weird I don't get affected by compliments...  non-suicide
2       Finally 2020 is almost over... So I can never ...  non-suicide
3               i need helpjust help me im crying so hard      suicide
4       I’m so lostHello, my name is Adam (16) and I’v...      suicide
...                                                   ...          ...
232069  If you don't like rock then your not going to ...  non-suicide
232070  You how you can tell i have so many friends an...  non-suicide
232071  pee probably tastes like salty tea😏💦‼️ can som...  non-suicide
232072  The usual stuff you find hereI'm not posting t...      suicide
232073  I still haven't beaten the first boss in Hollo...  non-suicide

[232074 rows x 2 columns]

In [8]:
df['cleaned_text'] = df['text'].apply(clean_text)

In [9]:
df

,text,class,cleaned_text
0,Ex Wife Threatening SuicideRecently I left my ...,suicide,ex wife threatening suiciderecently left wife ...
1,Am I weird I don't get affected by compliments...,non-suicide,weird dont get affected compliment coming some...
2,Finally 2020 is almost over... So I can never ...,non-suicide,finally almost never hear bad year ever swear ...
3,i need helpjust help me im crying so hard,suicide,need helpjust help im cry hard
4,"I’m so lostHello, my name is Adam (16) and I’v...",suicide,im losthello name adam ive struggling year im ...
...,...,...,...
232069,If you don't like rock then your not going to ...,non-suicide,dont like rock going get anything go
232070,You how you can tell i have so many friends an...,non-suicide,tell many friend lonely everything deprived pr...
232071,pee probably tastes like salty tea😏💦‼️ can som...,non-suicide,pee probably taste like salty tea someone dran...
232072,The usual stuff you find hereI'm not posting t...,suicide,usual stuff find hereim posting sympathy pity ...
232073,I still haven't beaten the first boss in Hollo...,non-suicide,still havent beaten first bos hollow knight iv...

In [10]:
df = df.drop(columns=['text'])

df = df[['cleaned_text', 'class']]

df = df.rename(columns={'cleaned_text': 'text'})

In [11]:
df

                                                     text        class
0       ex wife threatening suiciderecently left wife ...      suicide
1       weird dont get affected compliment coming some...  non-suicide
2       finally almost never hear bad year ever swear ...  non-suicide
3                          need helpjust help im cry hard      suicide
4       im losthello name adam ive struggling year im ...      suicide
...                                                   ...          ...
232069               dont like rock going get anything go  non-suicide
232070  tell many friend lonely everything deprived pr...  non-suicide
232071  pee probably taste like salty tea someone dran...  non-suicide
232072  usual stuff find hereim posting sympathy pity ...      suicide
232073  still havent beaten first bos hollow knight iv...  non-suicide

[232074 rows x 2 columns]

In [12]:
df.to_csv("../dataset/processed_dataset.csv", index=False)

In [15]:
df.isnull().sum()

text     0
class    0
dtype: int64

In [19]:
df

                                                     text        class
0       ex wife threatening suiciderecently left wife ...      suicide
1       weird dont get affected compliment coming some...  non-suicide
2       finally almost never hear bad year ever swear ...  non-suicide
3                          need helpjust help im cry hard      suicide
4       im losthello name adam ive struggling year im ...      suicide
...                                                   ...          ...
232069               dont like rock going get anything go  non-suicide
232070  tell many friend lonely everything deprived pr...  non-suicide
232071  pee probably taste like salty tea someone dran...  non-suicide
232072  usual stuff find hereim posting sympathy pity ...      suicide
232073  still havent beaten first bos hollow knight iv...  non-suicide

[232074 rows x 2 columns]